server {
    listen 80; #itu buka port 80
    listen [::]:80; #sama
    server_name _; #itu nama domain nya kalau _ itu tandanya dia tidak ada nama domain yang di daftarkan jadi mau dibuka pakai nama domain apa aja tetap bisa kebuka

    root /var/www/html/public; #itu root nya atau folder utama nya
    index index.php index.html index.htm; #itu index nya atau file utama nya

    charset utf-8;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    location / {
        try_files $uri $uri/ /index.php?$query_string; #itu location / nya atau folder utama nya kalau misal gak ada file nya dia akan mencari index.php
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # Pass PHP scripts to FastCGI server
    location ~ \.php$ {
        fastcgi_pass app:9000; 
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    # Block access to hidden files (.env, .git) and return 404 Not Found
    location ~ /\.(?!well-known).* {
        return 404;
    }
}
